In [1]:
import pandas as pd

a = pd.read_excel (r'I:\Pattern Lab\Project\merged.xlsx') #for an earlier version of Excel, you may need to use the file extension of 'xls'
a.head()

Timestamp  Score         ID  Gender Height  Weight  CGPA  \
0  3/23/2019 19:10:21  0 / 2  151341004     NaN    5.7     NaN   NaN   
1  3/24/2019 14:41:32  0 / 1  151341004    Male  5'6''    70.0  3.71   
2  3/24/2019 14:29:31  0 / 1  151341021    Male   5'3"    61.0  3.48   
3  3/24/2019 14:33:11  0 / 1  151341012    Male    5.8    78.0  2.90   
4  3/24/2019 14:34:00  0 / 1  151341008  Female    5.3    48.0  3.33   

  Daily spent time in social media (hour)    Hometown  \
0                                     NaN         NaN   
1                            Below 1 hour        Feni   
2                     2019-05-02 00:00:00  Lakshmipur   
3                            Below 1 hour  Munshiganj   
4                     2019-05-02 00:00:00    Bagerhat   

  How many days in a week you feel more energetic  \
0                                             NaN   
1                                               4   
2                                               4   
3                                               4   
4                                               3   

                  ...                 Current Place Latitude cp Longitude cp  \
0                 ...                      Lalmatia     23.7571      90.3685   
1                 ...                      Lalmatia     23.7571      90.3685   
2                 ...                      Rayerbag     23.6938      90.4553   
3                 ...                      Zigatola     23.7381      90.3725   
4                 ...                       Katasur     40.2824      -79.693   

  Place of interest Latitude pi  Longitude pi Leisure time activity  \
0       Switzerland     46.5475       7.98529             Fast Food   
1       Switzerland     46.5475       7.98529             Fast Food   
2             China      34.626        103.65          Regular Food   
3       Cox's Bazar     21.4339        91.987          Regular Food   
4         Bandarban    -7.73352       112.959       Kacchi Biriyani   

         Food you like most   Future plan Typically your days are started at:  
0                 Newspaper            HS                            09:00:00  
1                 Newspaper            HS                            09:00:00  
2  TV Series, Documentaries  Higher Study                            10.00 AM  
3                    Sports    Don't have                            09:00:00  
4                  Sleeping    Don't have                            06:00:00  

[5 rows x 81 columns]

In [2]:
b=a[['ID','Gender','CGPA','Hobby']]
b.head()

ID  Gender  CGPA                                              Hobby
0  151341004     NaN   NaN                                                NaN
1  151341004    Male  3.71                                     Playing guitar
2  151341021    Male  3.48  Watching TV Series, Anime, Documentaries. Maki...
3  151341012    Male  2.90                                          Traveling
4  151341008  Female  3.33                    Reading story books,travelling.

In [3]:
print(b)

            ID  Gender   CGPA  \
0    151341004     NaN    NaN   
1    151341004    Male  3.710   
2    151341021    Male  3.480   
3    151341012    Male  2.900   
4    151341008  Female  3.330   
5    151341011    Male  3.720   
6    151341029    Male  3.430   
7    151341005  Female  3.270   
8    151341006  Female  3.000   
9    151341023  Female  3.420   
10   151341009  Female  3.640   
11   151341014    Male  3.360   
12   151341026    Male  3.300   
13   151341019    Male  2.750   
14   151341013    Male  3.400   
15   151341022    Male  2.690   
16   151341027    Male  3.760   
17   151341015    Male  2.965   
18   151341037    Male  3.230   
19   151341038  Female  3.000   
20   151341035    Male  3.620   
21   141440899  Female  3.620   
22   141440945    Male  2.880   
23   151341028    Male  3.380   
24   151340998    Male  3.250   
25   151341000  Female  3.690   
26   151340977    Male  2.750   
27   151340983    Male  2.987   
28   151340981    Male  2.500   
29   15134

In [4]:
b.dropna()

ID  Gender   CGPA  \
1    151341004    Male  3.710   
2    151341021    Male  3.480   
3    151341012    Male  2.900   
4    151341008  Female  3.330   
5    151341011    Male  3.720   
6    151341029    Male  3.430   
7    151341005  Female  3.270   
8    151341006  Female  3.000   
9    151341023  Female  3.420   
10   151341009  Female  3.640   
11   151341014    Male  3.360   
12   151341026    Male  3.300   
13   151341019    Male  2.750   
14   151341013    Male  3.400   
15   151341022    Male  2.690   
16   151341027    Male  3.760   
17   151341015    Male  2.965   
18   151341037    Male  3.230   
19   151341038  Female  3.000   
20   151341035    Male  3.620   
21   141440899  Female  3.620   
22   141440945    Male  2.880   
23   151341028    Male  3.380   
24   151340998    Male  3.250   
25   151341000  Female  3.690   
26   151340977    Male  2.750   
27   151340983    Male  2.987   
28   151340981    Male  2.500   
29   151340988  Female  3.530   
30   151340994    Male  3.100   
..         ...     ...    ...   
71   151340934    Male  3.150   
72   151340945    Male  3.430   
73   151340931    Male  3.500   
74   151340926    Male  3.210   
75   151340944    Male  3.640   
76   151340942  Female  3.500   
77   151340932    Male  3.400   
78   151340933    Male  3.416   
79   151340923    Male  3.680   
80   151340935    Male  3.150   
81   151340943    Male  3.010   
82   151340947  Female  3.240   
83   151340937  Female  3.390   
84   151340939  Female  3.570   
85   151340921    Male  3.000   
86   141340900    Male  2.470   
87   151341039    Male  3.300   
88   151341020    Male  2.970   
89   151341045    Male  3.440   
90   151341017  Female  3.400   
91   131440969    Male  2.800   
92   151341016    Male  3.150   
93   121440946    Male  2.340   
94   151341010    Male  3.180   
95   151341040  Female  3.246   
96   151341043    Male  3.845   
97   131440910  Female  2.500   
99   141440980    Male  2.400   
100  151341036  Female  3.430   
102  151341044    Male  2.700   

                                                 Hobby  
1                                       Playing guitar  
2    Watching TV Series, Anime, Documentaries. Maki...  
3                                            Traveling  
4                      Reading story books,travelling.  
5                                not specific anything  
6                       Reading books, Watching movies  
7                                       playing violin  
8                                    browsing internet  
9                                        Reading Books  
10                             Reading, Petting animal  
11                 Watching movies, listening to music  
12                                             Drawing  
13                 Watching cricket and football on tv  
14                         anime, tv series and movies  
15                                  Travelling, Gaming  
16                                      Watching Movie  
17                                          Travelling  
18                                            coocking  
19                                            Painting  
20                                       Playing games  
21                                       Reading Books  
22                                    Playing Football  
23                                    Playing Football  
24                                  watching tv series  
25                                            painting  
26                                              Sports  
27                                            sleeping  
28                                      playing guitar  
29                               movies, music, travel  
30                                         Digital Art  
..                                                 ...  
71                       playing cricket, online games  
72                                     Playing Cricket  
73                         

In [5]:
b=a[['ID','Gender','CGPA','Hobby']]
b.head()

ID  Gender  CGPA                                              Hobby
0  151341004     NaN   NaN                                                NaN
1  151341004    Male  3.71                                     Playing guitar
2  151341021    Male  3.48  Watching TV Series, Anime, Documentaries. Maki...
3  151341012    Male  2.90                                          Traveling
4  151341008  Female  3.33                    Reading story books,travelling.

In [6]:
print(b)

            ID  Gender   CGPA  \
0    151341004     NaN    NaN   
1    151341004    Male  3.710   
2    151341021    Male  3.480   
3    151341012    Male  2.900   
4    151341008  Female  3.330   
5    151341011    Male  3.720   
6    151341029    Male  3.430   
7    151341005  Female  3.270   
8    151341006  Female  3.000   
9    151341023  Female  3.420   
10   151341009  Female  3.640   
11   151341014    Male  3.360   
12   151341026    Male  3.300   
13   151341019    Male  2.750   
14   151341013    Male  3.400   
15   151341022    Male  2.690   
16   151341027    Male  3.760   
17   151341015    Male  2.965   
18   151341037    Male  3.230   
19   151341038  Female  3.000   
20   151341035    Male  3.620   
21   141440899  Female  3.620   
22   141440945    Male  2.880   
23   151341028    Male  3.380   
24   151340998    Male  3.250   
25   151341000  Female  3.690   
26   151340977    Male  2.750   
27   151340983    Male  2.987   
28   151340981    Male  2.500   
29   15134

In [7]:
b.to_excel('selected_columns.xlsx')

In [11]:
c=b.dropna()
print(c)

            ID  Gender   CGPA  \
1    151341004    Male  3.710   
2    151341021    Male  3.480   
3    151341012    Male  2.900   
4    151341008  Female  3.330   
5    151341011    Male  3.720   
6    151341029    Male  3.430   
7    151341005  Female  3.270   
8    151341006  Female  3.000   
9    151341023  Female  3.420   
10   151341009  Female  3.640   
11   151341014    Male  3.360   
12   151341026    Male  3.300   
13   151341019    Male  2.750   
14   151341013    Male  3.400   
15   151341022    Male  2.690   
16   151341027    Male  3.760   
17   151341015    Male  2.965   
18   151341037    Male  3.230   
19   151341038  Female  3.000   
20   151341035    Male  3.620   
21   141440899  Female  3.620   
22   141440945    Male  2.880   
23   151341028    Male  3.380   
24   151340998    Male  3.250   
25   151341000  Female  3.690   
26   151340977    Male  2.750   
27   151340983    Male  2.987   
28   151340981    Male  2.500   
29   151340988  Female  3.530   
30   15134

In [12]:
c.to_excel('selected_columns_without_missing_value.xlsx')

In [16]:
from sklearn.preprocessing import StandardScaler 
import pandas 
import numpy 

names = ['ID', 'Gender', 'CGPA', 'Hobby'] 

array = c.values 
  
# separate array into input and output components 
X = array[:,0:3] 
Y = array[:,3] 
scaler = StandardScaler().fit(X) 
rescaledX = scaler.transform(X) 
  
# summarize transformed data 
numpy.set_printoptions(precision=3) 
print(rescaledX[0:5,:]) 

ValueError: could not convert string to float: 'Male'

In [17]:
c.Gender = c.Gender.astype(float)

ValueError: could not convert string to float: 'Male'

In [18]:
c['Gender'].apply(lambda x:float(x))

ValueError: could not convert string to float: 'Male'

In [19]:
c['Gender'] = c['Gender'].astype('category')
c.Gender = c.Gender.cat.rename_categories([0,1])


C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\User\Anaconda3\lib\site-packages\pandas\core\generic.py:4401: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [21]:
c.columns = ['ID','Gender','CGPA','Hobby']
c['Gender'] = c['Gender'].astype('category')
c.Gender = c.Gender.cat.rename_categories([0,1])

c.head()

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\User\Anaconda3\lib\site-packages\pandas\core\generic.py:4401: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


ID Gender  CGPA                                              Hobby
1  151341004      1  3.71                                     Playing guitar
2  151341021      1  3.48  Watching TV Series, Anime, Documentaries. Maki...
3  151341012      1  2.90                                          Traveling
4  151341008      0  3.33                    Reading story books,travelling.
5  151341011      1  3.72                              not specific anything

In [22]:
print(c)

            ID Gender   CGPA  \
1    151341004      1  3.710   
2    151341021      1  3.480   
3    151341012      1  2.900   
4    151341008      0  3.330   
5    151341011      1  3.720   
6    151341029      1  3.430   
7    151341005      0  3.270   
8    151341006      0  3.000   
9    151341023      0  3.420   
10   151341009      0  3.640   
11   151341014      1  3.360   
12   151341026      1  3.300   
13   151341019      1  2.750   
14   151341013      1  3.400   
15   151341022      1  2.690   
16   151341027      1  3.760   
17   151341015      1  2.965   
18   151341037      1  3.230   
19   151341038      0  3.000   
20   151341035      1  3.620   
21   141440899      0  3.620   
22   141440945      1  2.880   
23   151341028      1  3.380   
24   151340998      1  3.250   
25   151341000      0  3.690   
26   151340977      1  2.750   
27   151340983      1  2.987   
28   151340981      1  2.500   
29   151340988      0  3.530   
30   151340994      1  3.100   
..      

In [23]:
from sklearn.preprocessing import StandardScaler 
import pandas 
import numpy 

names = ['ID', 'Gender', 'CGPA', 'Hobby'] 

array = c.values 
  
# separate array into input and output components 
X = array[:,0:3] 
Y = array[:,3] 
scaler = StandardScaler().fit(X) 
rescaledX = scaler.transform(X) 
  
# summarize transformed data 
numpy.set_printoptions(precision=3) 
print(rescaledX[0:5,:]) 

[[ 0.251  0.718  1.35 ]
 [ 0.251  0.718  0.691]
 [ 0.251  0.718 -0.97 ]
 [ 0.251 -1.393  0.261]
 [ 0.251  0.718  1.378]]


C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [24]:
print(rescaledX)

[[ 2.511e-01  7.181e-01  1.350e+00]
 [ 2.511e-01  7.181e-01  6.909e-01]
 [ 2.511e-01  7.181e-01 -9.700e-01]
 [ 2.511e-01 -1.393e+00  2.614e-01]
 [ 2.511e-01  7.181e-01  1.378e+00]
 [ 2.511e-01  7.181e-01  5.477e-01]
 [ 2.511e-01 -1.393e+00  8.957e-02]
 [ 2.511e-01 -1.393e+00 -6.836e-01]
 [ 2.511e-01 -1.393e+00  5.191e-01]
 [ 2.511e-01 -1.393e+00  1.149e+00]
 [ 2.511e-01  7.181e-01  3.473e-01]
 [ 2.511e-01  7.181e-01  1.755e-01]
 [ 2.511e-01  7.181e-01 -1.400e+00]
 [ 2.511e-01  7.181e-01  4.618e-01]
 [ 2.511e-01  7.181e-01 -1.571e+00]
 [ 2.511e-01  7.181e-01  1.493e+00]
 [ 2.511e-01  7.181e-01 -7.838e-01]
 [ 2.511e-01  7.181e-01 -2.498e-02]
 [ 2.511e-01 -1.393e+00 -6.836e-01]
 [ 2.511e-01  7.181e-01  1.092e+00]
 [-1.953e+00 -1.393e+00  1.092e+00]
 [-1.953e+00  7.181e-01 -1.027e+00]
 [ 2.511e-01  7.181e-01  4.046e-01]
 [ 2.511e-01  7.181e-01  3.230e-02]
 [ 2.511e-01 -1.393e+00  1.292e+00]
 [ 2.511e-01  7.181e-01 -1.400e+00]
 [ 2.511e-01  7.181e-01 -7.208e-01]
 [ 2.511e-01  7.181e-01 -2.1

In [25]:
from sklearn.preprocessing import StandardScaler 
import pandas 
import numpy 

names = ['ID', 'Gender', 'CGPA', 'Hobby'] 

array = c.values 
  
# separate array into input and output components 
X = array[:,0:4] 
Y = array[:,3] 
scaler = StandardScaler().fit(X) 
rescaledX = scaler.transform(X) 
  
# summarize transformed data 
numpy.set_printoptions(precision=3) 
print(rescaledX[0:5,:]) 

ValueError: could not convert string to float: 'teaching student'

In [26]:
c.columns = ['ID','Gender','CGPA','Hobby']
c['Hobby'] = c['Hobby'].astype('category')
c.Hobby = c.Hobby.cat.rename_categories([0,1])

c.head()

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


ValueError: new categories need to have the same number of items as the old categories!

In [27]:
c.columns = ['ID','Gender','CGPA','Hobby']
c['Hobby'] = c['Hobby'].astype('category')
c.Hobby = c.Hobby.cat.rename_categories([0,1,2,3,4,5,6,7,8,9])

c.head()

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


ValueError: new categories need to have the same number of items as the old categories!

In [28]:
print(c)

            ID Gender   CGPA  \
1    151341004      1  3.710   
2    151341021      1  3.480   
3    151341012      1  2.900   
4    151341008      0  3.330   
5    151341011      1  3.720   
6    151341029      1  3.430   
7    151341005      0  3.270   
8    151341006      0  3.000   
9    151341023      0  3.420   
10   151341009      0  3.640   
11   151341014      1  3.360   
12   151341026      1  3.300   
13   151341019      1  2.750   
14   151341013      1  3.400   
15   151341022      1  2.690   
16   151341027      1  3.760   
17   151341015      1  2.965   
18   151341037      1  3.230   
19   151341038      0  3.000   
20   151341035      1  3.620   
21   141440899      0  3.620   
22   141440945      1  2.880   
23   151341028      1  3.380   
24   151340998      1  3.250   
25   151341000      0  3.690   
26   151340977      1  2.750   
27   151340983      1  2.987   
28   151340981      1  2.500   
29   151340988      0  3.530   
30   151340994      1  3.100   
..      

In [29]:
d=c[['Gender','CGPA','Hobby']]
d.head()

Gender  CGPA                                              Hobby
1      1  3.71                                     Playing guitar
2      1  3.48  Watching TV Series, Anime, Documentaries. Maki...
3      1  2.90                                          Traveling
4      0  3.33                    Reading story books,travelling.
5      1  3.72                              not specific anything

In [30]:
d.to_excel('binarized_gender.xlsx')

In [31]:
d.loc[d.Hobby == 'reading'||'Reading', 'name_match'] = 1 
d.loc[d.Hobby != 'reading'||'Reading', 'name_match'] = 0
 
print (df)

SyntaxError: invalid syntax (<ipython-input-31-921386096cf7>, line 1)

In [32]:
d.loc[d.Hobby == 'reading', 'name_match'] = 1 
d.loc[d.Hobby != 'reading', 'name_match'] = 0
 
print (df)

NameError: name 'df' is not defined

In [33]:
d.loc[d.Hobby == 'reading', 'name_match'] = 1 
d.loc[d.Hobby != 'reading', 'name_match'] = 0
 
print (d)

    Gender   CGPA                                              Hobby  \
1        1  3.710                                     Playing guitar   
2        1  3.480  Watching TV Series, Anime, Documentaries. Maki...   
3        1  2.900                                          Traveling   
4        0  3.330                    Reading story books,travelling.   
5        1  3.720                              not specific anything   
6        1  3.430                     Reading books, Watching movies   
7        0  3.270                                     playing violin   
8        0  3.000                                  browsing internet   
9        0  3.420                                      Reading Books   
10       0  3.640                            Reading, Petting animal   
11       1  3.360                Watching movies, listening to music   
12       1  3.300                                            Drawing   
13       1  2.750                Watching cricket and football o

In [1]:
d.loc[d.Hobby == 'reading', 'name_match'] = 'Reading'
d.loc[d.Hobby != 'reading', 'name_match'] = 'Not reading'
 
print (d)

NameError: name 'd' is not defined

In [2]:
d=c[['Gender','CGPA','Hobby']]
d.head()

NameError: name 'c' is not defined

In [3]:
import pandas as pd

d = pd.read_excel (r'I:\Pattern Lab\Project\binarized_gender.xlsx') #for an earlier version of Excel, you may need to use the file extension of 'xls'
d.head()

Gender  CGPA                                              Hobby
1       1  3.71                                     Playing guitar
2       1  3.48  Watching TV Series, Anime, Documentaries. Maki...
3       1  2.90                                          Traveling
4       0  3.33                    Reading story books,travelling.
5       1  3.72                              not specific anything

In [4]:
d.loc[d.Hobby == 'Reading', 'name_match'] = 'Reading'
d.loc[d.Hobby != 'Reading', 'name_match'] = 'Not reading'
 
print (d)

     Gender   CGPA                                              Hobby  \
1         1  3.710                                     Playing guitar   
2         1  3.480  Watching TV Series, Anime, Documentaries. Maki...   
3         1  2.900                                          Traveling   
4         0  3.330                    Reading story books,travelling.   
5         1  3.720                              not specific anything   
6         1  3.430                     Reading books, Watching movies   
7         0  3.270                                     playing violin   
8         0  3.000                                  browsing internet   
9         0  3.420                                      Reading Books   
10        0  3.640                            Reading, Petting animal   
11        1  3.360                Watching movies, listening to music   
12        1  3.300                                            Drawing   
13        1  2.750                Watching cricket 

In [5]:
d.loc[d.Hobby == '%Reading%', 'name_match'] = 'Reading'
d.loc[d.Hobby != '%Reading%', 'name_match'] = 'Not reading'
 
print (d)

     Gender   CGPA                                              Hobby  \
1         1  3.710                                     Playing guitar   
2         1  3.480  Watching TV Series, Anime, Documentaries. Maki...   
3         1  2.900                                          Traveling   
4         0  3.330                    Reading story books,travelling.   
5         1  3.720                              not specific anything   
6         1  3.430                     Reading books, Watching movies   
7         0  3.270                                     playing violin   
8         0  3.000                                  browsing internet   
9         0  3.420                                      Reading Books   
10        0  3.640                            Reading, Petting animal   
11        1  3.360                Watching movies, listening to music   
12        1  3.300                                            Drawing   
13        1  2.750                Watching cricket 

In [6]:
d[d['Hobby'].str.contains('eading')]

Gender   CGPA                                    Hobby   name_match
4        0  3.330          Reading story books,travelling.  Not reading
6        1  3.430           Reading books, Watching movies  Not reading
9        0  3.420                            Reading Books  Not reading
10       0  3.640                  Reading, Petting animal  Not reading
21       0  3.620                            Reading Books  Not reading
34       1  3.050                   Reading,Writing,Gaming  Not reading
40       0  3.450                             reading book  Not reading
44       0  3.770                            Reading Books  Not reading
46       1  3.530                        Reading Newspaper  Not reading
49       1  3.000                            Reading books  Not reading
55       0  3.400                             Reading book  Not reading
80       1  3.150  Reading books, hanging out with friends  Not reading
83       0  3.390                       Reading, Traveling  Not reading
90       0  3.400                             Reading book  Not reading
91       1  2.800                             Reading book  Not reading
95       0  3.246                            Reading Books  Not reading

In [7]:
import pandas as pd

d = pd.read_excel (r'I:\Pattern Lab\Project\binarized_gender.xlsx') #for an earlier version of Excel, you may need to use the file extension of 'xls'
d.head()

Gender  CGPA                                              Hobby
1       1  3.71                                     Playing guitar
2       1  3.48  Watching TV Series, Anime, Documentaries. Maki...
3       1  2.90                                          Traveling
4       0  3.33                    Reading story books,travelling.
5       1  3.72                              not specific anything

In [8]:
d.loc[d['Hobby'].str.contains('eading')], 'name_match'] = 'Reading'
d.loc[d['Hobby'].str.contains!('eading')], 'name_match'] = 'Not reading'
print (d)

SyntaxError: invalid syntax (<ipython-input-8-1452ba04277e>, line 1)

In [10]:
d[d['Hobby'].str.contains('eading'),'n']='Reading'

print (d)

TypeError: 'Series' objects are mutable, thus they cannot be hashed

In [11]:
d['Hobby'].str.contains('eading',regex=True)

1      False
2      False
3      False
4       True
5      False
6       True
7      False
8      False
9       True
10      True
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21      True
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
       ...  
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80      True
81     False
82     False
83      True
84     False
85     False
86     False
87     False
88     False
89     False
90      True
91      True
92     False
93     False
94     False
95      True
96     False
97     False
99     False
100    False
102    False
Name: Hobby, Length: 97, dtype: bool

In [12]:
d[d['Hobby'].str.contains('eading',regex=True)]
print(d)

     Gender   CGPA                                              Hobby
1         1  3.710                                     Playing guitar
2         1  3.480  Watching TV Series, Anime, Documentaries. Maki...
3         1  2.900                                          Traveling
4         0  3.330                    Reading story books,travelling.
5         1  3.720                              not specific anything
6         1  3.430                     Reading books, Watching movies
7         0  3.270                                     playing violin
8         0  3.000                                  browsing internet
9         0  3.420                                      Reading Books
10        0  3.640                            Reading, Petting animal
11        1  3.360                Watching movies, listening to music
12        1  3.300                                            Drawing
13        1  2.750                Watching cricket and football on tv
14        1  3.400  

In [13]:
e=d['Hobby'].str.contains('eading',regex=True)
print(e)

1      False
2      False
3      False
4       True
5      False
6       True
7      False
8      False
9       True
10      True
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21      True
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
       ...  
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80      True
81     False
82     False
83      True
84     False
85     False
86     False
87     False
88     False
89     False
90      True
91      True
92     False
93     False
94     False
95      True
96     False
97     False
99     False
100    False
102    False
Name: Hobby, Length: 97, dtype: bool


In [14]:
f=pd.merge(d,e)
print(f)

ValueError: can not merge DataFrame with instance of type <class 'pandas.core.series.Series'>

In [15]:
d[d['Hobby'].str.contains("eading")]

Gender   CGPA                                    Hobby
4        0  3.330          Reading story books,travelling.
6        1  3.430           Reading books, Watching movies
9        0  3.420                            Reading Books
10       0  3.640                  Reading, Petting animal
21       0  3.620                            Reading Books
34       1  3.050                   Reading,Writing,Gaming
40       0  3.450                             reading book
44       0  3.770                            Reading Books
46       1  3.530                        Reading Newspaper
49       1  3.000                            Reading books
55       0  3.400                             Reading book
80       1  3.150  Reading books, hanging out with friends
83       0  3.390                       Reading, Traveling
90       0  3.400                             Reading book
91       1  2.800                             Reading book
95       0  3.246                            Reading Books

In [16]:
d[d['Hobby'].str.contains("eading")==True]

Gender   CGPA                                    Hobby
4        0  3.330          Reading story books,travelling.
6        1  3.430           Reading books, Watching movies
9        0  3.420                            Reading Books
10       0  3.640                  Reading, Petting animal
21       0  3.620                            Reading Books
34       1  3.050                   Reading,Writing,Gaming
40       0  3.450                             reading book
44       0  3.770                            Reading Books
46       1  3.530                        Reading Newspaper
49       1  3.000                            Reading books
55       0  3.400                             Reading book
80       1  3.150  Reading books, hanging out with friends
83       0  3.390                       Reading, Traveling
90       0  3.400                             Reading book
91       1  2.800                             Reading book
95       0  3.246                            Reading Books

In [17]:
d[d['Hobby'].str.contains("eading")]
print(d)

     Gender   CGPA                                              Hobby
1         1  3.710                                     Playing guitar
2         1  3.480  Watching TV Series, Anime, Documentaries. Maki...
3         1  2.900                                          Traveling
4         0  3.330                    Reading story books,travelling.
5         1  3.720                              not specific anything
6         1  3.430                     Reading books, Watching movies
7         0  3.270                                     playing violin
8         0  3.000                                  browsing internet
9         0  3.420                                      Reading Books
10        0  3.640                            Reading, Petting animal
11        1  3.360                Watching movies, listening to music
12        1  3.300                                            Drawing
13        1  2.750                Watching cricket and football on tv
14        1  3.400  

In [18]:
e=d[d['Hobby'].str.contains("eading")]
e.columns = ['Gender','CGPA','Hobby']
e['Gender'] = e['Gender'].astype('category')
e.Gender = e.Gender.cat.rename_categories([1])

e.head()

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


ValueError: new categories need to have the same number of items as the old categories!

In [19]:
d.columns = ['Gender','CGPA','Hobby']
d['Gender'] = d['Gender'].str.contains("eading")].astype('category')
d.Gender = d.Gender.cat.rename_categories([0,1])

d.head()

SyntaxError: invalid syntax (<ipython-input-19-d51319b2f4b2>, line 2)

In [20]:
e=d[d['Hobby'].str.contains("eading")]
e.columns = ['Gender','CGPA','Hobby']
e['Hobby'] = e['Hobby'].astype('category')
e.Hobby = e.Hobby.cat.rename_categories([1])

e.head()

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


ValueError: new categories need to have the same number of items as the old categories!

In [21]:
import numpy as np
d['Match'] = np.where(d['Hobby'].str.contains("eading"), 'yes', 'no')
print(d)

     Gender   CGPA                                              Hobby Match
1         1  3.710                                     Playing guitar    no
2         1  3.480  Watching TV Series, Anime, Documentaries. Maki...    no
3         1  2.900                                          Traveling    no
4         0  3.330                    Reading story books,travelling.   yes
5         1  3.720                              not specific anything    no
6         1  3.430                     Reading books, Watching movies   yes
7         0  3.270                                     playing violin    no
8         0  3.000                                  browsing internet    no
9         0  3.420                                      Reading Books   yes
10        0  3.640                            Reading, Petting animal   yes
11        1  3.360                Watching movies, listening to music    no
12        1  3.300                                            Drawing    no
13        1 

In [22]:
d['Reading_Match'] = np.where(d['Hobby'].str.contains("eading"), 'yes', 'no')
print(d)

     Gender   CGPA                                              Hobby Match  \
1         1  3.710                                     Playing guitar    no   
2         1  3.480  Watching TV Series, Anime, Documentaries. Maki...    no   
3         1  2.900                                          Traveling    no   
4         0  3.330                    Reading story books,travelling.   yes   
5         1  3.720                              not specific anything    no   
6         1  3.430                     Reading books, Watching movies   yes   
7         0  3.270                                     playing violin    no   
8         0  3.000                                  browsing internet    no   
9         0  3.420                                      Reading Books   yes   
10        0  3.640                            Reading, Petting animal   yes   
11        1  3.360                Watching movies, listening to music    no   
12        1  3.300                                  

In [23]:
import pandas as pd

d = pd.read_excel (r'I:\Pattern Lab\Project\binarized_gender.xlsx') #for an earlier version of Excel, you may need to use the file extension of 'xls'
d.head()

Gender  CGPA                                              Hobby
1       1  3.71                                     Playing guitar
2       1  3.48  Watching TV Series, Anime, Documentaries. Maki...
3       1  2.90                                          Traveling
4       0  3.33                    Reading story books,travelling.
5       1  3.72                              not specific anything

In [24]:
d['Reading_Hobby'] = np.where(d['Hobby'].str.contains("eading"), 'yes', 'no')
print(d)

     Gender   CGPA                                              Hobby  \
1         1  3.710                                     Playing guitar   
2         1  3.480  Watching TV Series, Anime, Documentaries. Maki...   
3         1  2.900                                          Traveling   
4         0  3.330                    Reading story books,travelling.   
5         1  3.720                              not specific anything   
6         1  3.430                     Reading books, Watching movies   
7         0  3.270                                     playing violin   
8         0  3.000                                  browsing internet   
9         0  3.420                                      Reading Books   
10        0  3.640                            Reading, Petting animal   
11        1  3.360                Watching movies, listening to music   
12        1  3.300                                            Drawing   
13        1  2.750                Watching cricket 

In [25]:
d[['Gender','CGPA','Reading_Hobby']]
print(d)

     Gender   CGPA                                              Hobby  \
1         1  3.710                                     Playing guitar   
2         1  3.480  Watching TV Series, Anime, Documentaries. Maki...   
3         1  2.900                                          Traveling   
4         0  3.330                    Reading story books,travelling.   
5         1  3.720                              not specific anything   
6         1  3.430                     Reading books, Watching movies   
7         0  3.270                                     playing violin   
8         0  3.000                                  browsing internet   
9         0  3.420                                      Reading Books   
10        0  3.640                            Reading, Petting animal   
11        1  3.360                Watching movies, listening to music   
12        1  3.300                                            Drawing   
13        1  2.750                Watching cricket 

In [26]:
e=d[['Gender','CGPA','Reading_Hobby']]
print(e)

     Gender   CGPA Reading_Hobby
1         1  3.710            no
2         1  3.480            no
3         1  2.900            no
4         0  3.330           yes
5         1  3.720            no
6         1  3.430           yes
7         0  3.270            no
8         0  3.000            no
9         0  3.420           yes
10        0  3.640           yes
11        1  3.360            no
12        1  3.300            no
13        1  2.750            no
14        1  3.400            no
15        1  2.690            no
16        1  3.760            no
17        1  2.965            no
18        1  3.230            no
19        0  3.000            no
20        1  3.620            no
21        0  3.620           yes
22        1  2.880            no
23        1  3.380            no
24        1  3.250            no
25        0  3.690            no
26        1  2.750            no
27        1  2.987            no
28        1  2.500            no
29        0  3.530            no
30        

In [27]:
e.to_excel('reading_hobby.xlsx')